sudo: false
language: node_js
node_js: 7
install:
  - npm install -g bower grunt-cli
  - npm install phantomjs-prebuilt
  - npm install
  - bower install
  - gem install compass
  - bower list
  - npm list
script:
  - grunt test
  - grunt build
  - SCRIPTS_FN=`ls dist/scripts/scripts*.js`
  - sed "s/WENFO_GOOGLE_MAPS_API_KEY/$GOOGLE_MAPS_API_KEY/g" < $SCRIPTS_FN > tmp
  - mv tmp $SCRIPTS_FN
deploy:
  # deploy to "wenfo.org/staging/aus-env" on branch master
  - skip_cleanup: true
    provider: script
    script: bash -c "cd dist && find . -type f -exec curl -u $FTP_USER:$FTP_PASSWORD --ftp-create-dirs -T {} ftp.wenfo.org/staging/{} \;"
    on:
      branch: master
  # deploy to "wenfo.org/aus-env" on branch production
  - skip_cleanup: true
    provider: script
    script: bash -c "cd dist && find . -type f -exec curl -u $FTP_USER:$FTP_PASSWORD --ftp-create-dirs -T {} ftp.wenfo.org{} \;"
    on:
      branch: production
notifications:
  email: false
  slack:
    rooms:
      secure: HQRnvE4qt9ksg3uiJP/t7W3wM+yZsrkDBIjrsFW1BlenWfglFvXafb0sFuW4VtsOLra0pDqTaGy6uwrs21YvmilN4U2zS3opco1KIFR/3W/PWeROuOQVuJFIP/8AE21pEP66w7ebWZmpAnf3JGqrKroImmX1OqadWTIBunzEPz97MXkMAwXpviMHNVFPCuyft/4OZr8l3N+i9UvlFERNCvbkCZNmhKiuGtalAsqTC/BTSUYTBov9/PwL8ELucvquHPQXejcOo9HrBMK2arMyqmgjXhXif3DUldZNy4PmD7nPP6hzDCSKEMVJH1x3DTqBBGc5BHsghc4XD9aY4IZCachZkb4bCA1eAeMrR0z43e0YsA0alWWQskTArerC3Ex5Ci5Ny7X6zld2iKdFU7oBNR0zHUDcOMa7yI9lhJF1cya5tNOURRPnoj1jvCiOnAkDQqC1RPl68tjajxJeJSllSeP4HiOYvVVWKwZxXs6J1RcRsTVxIpB5CeR5uoglCC3drcU98+LLJL3ydEn7feKfXTcbrSX1tgjfJJ1PXZTgGXimahaZFqNKjDxvYhtcIlAOHd/WeWnXFtzvslDzUNFmleD3a1/86S5H5BG338wdzApccKbHqi5iojQnS8iY46TODJrQlNSxkROjGFsIwsR62EpYzPadDOp325fszYKxGyA=
    on_success: always
