sudo: false
language: node_js
node_js:
  - 'iojs'
  - '0.12'
  - '0.10'
install:
  - npm install -g bower grunt-cli
  - npm install
  - bower install
  - gem install compass
script:
  - grunt test
  - grunt build
deploy:
  skip_cleanup: true
notifications:
  email: false
  slack:
    rooms: wenfo:N1YfzQWaJ8wfjvrYarrh33PZ
    on_success: change
